3.5
An error occurred while executing the following cell:
------------------
x
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-16-6fcf9dfbd479>[0m in [0;36m<module>[0;34m()[0m
[0;32m----> 1[0;31m [0mx[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'x' is not defined
NameError: name 'x' is not defined

Executability                            : False
