3.5
An error occurred while executing the following cell:
------------------
drame1
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-3-eddb5f77b590>[0m in [0;36m<module>[0;34m()[0m
[0;32m----> 1[0;31m [0mdrame1[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'drame1' is not defined
NameError: name 'drame1' is not defined

Executability                            : False
