3.5
An error occurred while executing the following cell:
------------------
X_train, y_train = load_mnist('C:\\Users\\309292\\Desktop\\Python\\MNIST', kind='train')
print('Rows: %d, columns: %d' % (X_train.shape[0], X_train.shape[1]))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mOSError[0m                                   Traceback (most recent call last)
[0;32m<ipython-input-3-7695d83a308e>[0m in [0;36m<module>[0;34m()[0m
[0;32m----> 1[0;31m [0mX_train[0m[0;34m,[0m [0my_train[0m [0;34m=[0m [0mload_mnist[0m[0;34m([0m[0;34m'C:\\Users\\309292\\Desktop\\Python\\MNIST'[0m[0;34m,[0m [0mkind[0m[0;34m=[0m[0;34m'train'[0m[0;34m)[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mprint[0m[0;34m([0m[0;34m'Rows: %d, columns: %d'[0m [0;34m%[0m [0;34m([0m[0mX_train[0m[0;34m.[0m[0mshape[0m[0;34m[[0m[0;36m0[0m[0;34m][0m[0;34m,[0m [0mX_train[0m[0;34m.[0m[0mshape[0m[0;34m[[0m[0;36m1[0m[0;34m][0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0m

[0;32m<ipython-input-2-2b44ba080bf1>[0m in [0;36mload_mnist[0;34m(path, kind)[0m
[1;32m     12[0m                                '%s-images.idx3-ubyte' % kind)
[1;32m     13[0m [0;34m[0m[0m
[0;32m---> 14[0;31m     [0;32mwith[0m [0mopen[0m[0;34m([0m[0mlabels_path[0m[0;34m,[0m [0;34m'rb'[0m[0;34m)[0m [0;32mas[0m [0mlbpath[0m[0;34m:[0m[0;34m[0m[0m
[0m[1;32m     15[0m         magic, n = struct.unpack('>II', 
[1;32m     16[0m                                  lbpath.read(8))

[0;31mOSError[0m: [Errno 22] Invalid argument: 'C:\\Users\\309292\\Desktop\\Python\\MNIST/train-labels.idx1-ubyte'
OSError: [Errno 22] Invalid argument: 'C:\\Users\\309292\\Desktop\\Python\\MNIST/train-labels.idx1-ubyte'

Executability                            : False
