3.5
An error occurred while executing the following cell:
------------------
import warnings
warnings.filterwarnings('ignore')
products = products.fillna({'review':''})  # fill in N/A's in the review column
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-1-c540321e1fa1>[0m in [0;36m<module>[0;34m()[0m
[1;32m      1[0m [0;32mimport[0m [0mwarnings[0m[0;34m[0m[0m
[1;32m      2[0m [0mwarnings[0m[0;34m.[0m[0mfilterwarnings[0m[0;34m([0m[0;34m'ignore'[0m[0;34m)[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0mproducts[0m [0;34m=[0m [0mproducts[0m[0;34m.[0m[0mfillna[0m[0;34m([0m[0;34m{[0m[0;34m'review'[0m[0;34m:[0m[0;34m''[0m[0;34m}[0m[0;34m)[0m  [0;31m# fill in N/A's in the review column[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'products' is not defined
NameError: name 'products' is not defined

Executability                            : False
