3.5
An error occurred while executing the following cell:
------------------
import warnings
warnings.filterwarnings('ignore')
from matplotlib import pyplot as plt
from scipy.stats import norm
from scipy.optimize import root, fsolve
from scipy import stats

import numba as nb
import numpy as np
import pandas as pd

%matplotlib inline
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
[0;32m<ipython-input-1-aed0e536da91>[0m in [0;36m<module>[0;34m()[0m
[1;32m      6[0m [0;32mfrom[0m [0mscipy[0m [0;32mimport[0m [0mstats[0m[0;34m[0m[0m
[1;32m      7[0m [0;34m[0m[0m
[0;32m----> 8[0;31m [0;32mimport[0m [0mnumba[0m [0;32mas[0m [0mnb[0m[0;34m[0m[0m
[0m[1;32m      9[0m [0;32mimport[0m [0mnumpy[0m [0;32mas[0m [0mnp[0m[0;34m[0m[0m
[1;32m     10[0m [0;32mimport[0m [0mpandas[0m [0;32mas[0m [0mpd[0m[0;34m[0m[0m

[0;31mImportError[0m: No module named 'numba'
ImportError: No module named 'numba'

Executability                            : False
