3.6
An error occurred while executing the following cell:
------------------
import warnings
warnings.filterwarnings('ignore')
with open('./nhlTeamCallSign.json', 'r') as fp:
    teams = json.load(fp)
    
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-1-da0b745f3925>[0m in [0;36m<module>[0;34m[0m
[1;32m      2[0m [0mwarnings[0m[0;34m.[0m[0mfilterwarnings[0m[0;34m([0m[0;34m'ignore'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;32mwith[0m [0mopen[0m[0;34m([0m[0;34m'./nhlTeamCallSign.json'[0m[0;34m,[0m [0;34m'r'[0m[0;34m)[0m [0;32mas[0m [0mfp[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 4[0;31m     [0mteams[0m [0;34m=[0m [0mjson[0m[0;34m.[0m[0mload[0m[0;34m([0m[0mfp[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      5[0m [0;34m[0m[0m

[0;31mNameError[0m: name 'json' is not defined
NameError: name 'json' is not defined

Executability                            : False
