3.6
An error occurred while executing the following cell:
------------------
import warnings
warnings.filterwarnings('ignore')
f = open('data.txt')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m<ipython-input-1-7d4c07da7f6e>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mimport[0m [0mwarnings[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0mwarnings[0m[0;34m.[0m[0mfilterwarnings[0m[0;34m([0m[0;34m'ignore'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 3[0;31m [0mf[0m [0;34m=[0m [0mopen[0m[0;34m([0m[0;34m'data.txt'[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'data.txt'
FileNotFoundError: [Errno 2] No such file or directory: 'data.txt'

Executability                            : False
