3.5
An error occurred while executing the following cell:
------------------
import warnings
warnings.filterwarnings('ignore')
#Import Dependencies
import json
import requests
from citipy import citipy
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import time
from datetime import timedelta,datetime,date
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
[0;32m<ipython-input-1-818fca93d751>[0m in [0;36m<module>[0;34m()[0m
[1;32m      4[0m [0;32mimport[0m [0mjson[0m[0;34m[0m[0m
[1;32m      5[0m [0;32mimport[0m [0mrequests[0m[0;34m[0m[0m
[0;32m----> 6[0;31m [0;32mfrom[0m [0mcitipy[0m [0;32mimport[0m [0mcitipy[0m[0;34m[0m[0m
[0m[1;32m      7[0m [0;32mimport[0m [0mpandas[0m [0;32mas[0m [0mpd[0m[0;34m[0m[0m
[1;32m      8[0m [0;32mimport[0m [0mnumpy[0m [0;32mas[0m [0mnp[0m[0;34m[0m[0m

[0;31mImportError[0m: No module named 'citipy'
ImportError: No module named 'citipy'

Executability                            : False
